### ISSUE TITLE
Free telegram Stable Diffusion bots

### ISSUE THREAD

**Issue by doevent** [mixa3607/SdHub#2]
Free telegram SD bots:

@stable_diffusion_bot
@StableDiffusionWrapperBot
@mts_stable_diffusion_bot
@txt2image_exhuman_bot
@StableDiffusionPic_bot
@neuro_sich_bot
@CraiyonArtBot
@txt2avatar_exhuman_bot
@piratediffusion
@easydalle2bot
@sber_rudalle_xl_bot

**Comment by mixa3607** [comment]
Добавлено
