### ISSUE TITLE
Обновление шапки

### ISSUE THREAD

**Issue by urBestFren** [mixa3607/SdHub#5]
Предлагается вести открытый каталог генераций с промптами, чтобы любой желающий мог зайти и ознакомиться с наследием ушедших тредов. Анон уже запилил такой https://diffai.xyz/gen/search, на мой взгляд это более благоприятная замена потерявшемуся архиву с богинями треда, который некогда был в шапке.
Также есть мысль вынести в шапку немного деталей из sd resource goldmine, так как многие новички обладают слабым уровнем английского и не хотят/не могут копаться в довольно объёмной базе. Отсюда предлагаю добавить в шапку ссылку на каталог вайлдкарт https://rentry.org/NAIwildcards и, возможно, ссылку на документ с разбором влияния тегов на генерацию https://files.catbox.moe/hqs4yf.pdf.

**Comment by mixa3607** [comment]
@urBestFren 
1. Как мог заметить код от [https://diffai.xyz](https://diffai.xyz) как раз в этом репо. Когда будут добавлены альбомы внесу изменения в шапку
2. Предложенные ссылки добавил на страницу на вики созданную вследствие #4

Спасибо за участие
